// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StraniVari.Database;

#nullable disable

namespace StraniVari.Database.Migrations
{
    [DbContext(typeof(StraniVariDbContext))]
    partial class StraniVariDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "Administrator",
                            Name = "Administrator",
                            NormalizedName = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "RegularUser",
                            Name = "RegularUser",
                            NormalizedName = "RegularUser"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StraniVari.Core.Entities.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Administrators");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ulica zlatnih ljiljana",
                            City = "Zavidovici",
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(3118),
                            DateOfBirth = new DateTime(2022, 10, 30, 18, 40, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Admin",
                            LastName = "Admin"
                        });
                });

            modelBuilder.Entity("StraniVari.Core.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StraniVariTheme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2533),
                            EndDate = new DateTime(2020, 5, 13, 3, 32, 0, 0, DateTimeKind.Unspecified),
                            Name = "Strani Vari 2019",
                            StartDate = new DateTime(2022, 9, 2, 17, 45, 0, 0, DateTimeKind.Unspecified),
                            StraniVariTheme = "Cartoon characters"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2548),
                            EndDate = new DateTime(2020, 10, 2, 17, 6, 0, 0, DateTimeKind.Unspecified),
                            Name = "Strani Vari 2020",
                            StartDate = new DateTime(2021, 12, 10, 12, 38, 0, 0, DateTimeKind.Unspecified),
                            StraniVariTheme = "Favourite activity"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2550),
                            EndDate = new DateTime(2020, 2, 28, 17, 13, 0, 0, DateTimeKind.Unspecified),
                            Name = "Strani Vari 2021",
                            StartDate = new DateTime(2022, 10, 7, 7, 21, 0, 0, DateTimeKind.Unspecified),
                            StraniVariTheme = "Circus"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2552),
                            EndDate = new DateTime(2022, 9, 26, 17, 48, 0, 0, DateTimeKind.Unspecified),
                            Name = "Strani Vari 2022",
                            StartDate = new DateTime(2020, 12, 29, 14, 34, 0, 0, DateTimeKind.Unspecified),
                            StraniVariTheme = "Favourite cartoon"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2553),
                            EndDate = new DateTime(2020, 12, 25, 22, 35, 0, 0, DateTimeKind.Unspecified),
                            Name = "Strani Vari 2018",
                            StartDate = new DateTime(2020, 10, 9, 15, 37, 0, 0, DateTimeKind.Unspecified),
                            StraniVariTheme = "Health"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2556),
                            EndDate = new DateTime(2023, 10, 24, 19, 36, 0, 0, DateTimeKind.Unspecified),
                            Name = "Strani Vari 2023",
                            StartDate = new DateTime(2023, 9, 8, 9, 13, 0, 0, DateTimeKind.Unspecified),
                            StraniVariTheme = "Elements"
                        });
                });

            modelBuilder.Entity("StraniVari.Core.Entities.EventSchool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfChildren")
                        .HasColumnType("int");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("SchoolId");

                    b.ToTable("EventSchools");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2665),
                            EventId = 4,
                            NumberOfChildren = 80,
                            SchoolId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2672),
                            EventId = 3,
                            NumberOfChildren = 50,
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2674),
                            EventId = 1,
                            NumberOfChildren = 123,
                            SchoolId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2678),
                            EventId = 4,
                            NumberOfChildren = 80,
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2684),
                            EventId = 6,
                            NumberOfChildren = 50,
                            SchoolId = 2
                        });
                });

            modelBuilder.Entity("StraniVari.Core.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2410),
                            Name = "Fudbal",
                            Rules = "Svaka se ekipa sastoji od najviše 11 igrača (ne zamjena tj. rezervi), od kojih jedan mora biti golman. Pravila takmičenja određuju minimalan broj igrača koji je potreban za stvaranje ekipe, što je najčešće sedam."
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2453),
                            Name = "Pitalice s loptom",
                            Rules = "Uzmite loptu i preko nje zalijepite bijeli papir sa selotejpom. Napišite djeci. Neka djeca sjednu u krug i bacaju loptu. Kad uhvate loptu, moraju odgovoriti na pitanje najbliže desnom kažiprstu. Nakon odgovora, opet bacaju loptu. Možete na lopti napisati brojeve, a pitanja posebno na papiru ako vam je tako lakše."
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2455),
                            Name = "Pogodi tko sam – igra imitacije i pogađanja",
                            Rules = "Riječ je o pantomimi gdje jedna osoba glumi neku drugu osobu koju ostali igrači znaju. Sve je dozvoljeno osim razgovora."
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2457),
                            Name = "Crtanje zavezanih očiju",
                            Rules = "Na dječjoj ploči ili većem komadu papira organizirajte igru u kojoj ćete se izmjenjivati u crtanju. Preostali igrači neke redom zadaju zadatke. U igri nema bodova i pobjednika, cilj je dobra zabava."
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2458),
                            Name = "Izmedju dvije vatre",
                            Rules = "U igri učestvuje osam (8) igrača, sedam (7) u svojoj polovici terena za igru i jedan graničar. Graničar se nalazi iza linije terena za igre na suprotnoj strani od polovice terena za igru gdje se nalazi njegova ekipa. Suparnička ekipa nalazi se između graničara i njegove ekipe.Cilj igre je da svaka ekipa rukom bačenu loptu neobranjivo pogađa igrače suparničke ekipe u njihovom polju,a da izbjegnu iste namjere suparničke ekipe.Meč se igra na ispadanje,tačnije kada protivnička ekipa pogodi igrača,igrač ispada i meč se igra sve dok se ne pogodi i posljedni igrač u polju."
                        });
                });

            modelBuilder.Entity("StraniVari.Core.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2708),
                            Name = "Vodene bojice"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2711),
                            Name = "Papir u boji"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2712),
                            Name = "Lopte"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2713),
                            Name = "Reketi"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2715),
                            Name = "Flomasteri"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2717),
                            Name = "Bojice"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2718),
                            Name = "Hamer papir"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2719),
                            Name = "Face paint"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2720),
                            Name = "Glina"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2722),
                            Name = "Plastelin"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2724),
                            Name = "Siljalo"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2725),
                            Name = "Makaze"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2726),
                            Name = "Kolaz papir"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2727),
                            Name = "Platno"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2728),
                            Name = "Bijeli papir"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2729),
                            Name = "Krede"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2731),
                            Name = "Heftarica"
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2733),
                            Name = "Bijeli papir"
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2734),
                            Name = "Baloni"
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2735),
                            Name = "Tempere"
                        });
                });

            modelBuilder.Entity("StraniVari.Core.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MeetingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MeetingPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingTheme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Roncadelle",
                            City = "Zavidovici",
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2804),
                            EventId = 2,
                            MeetingDate = new DateTime(2022, 3, 11, 19, 42, 0, 0, DateTimeKind.Unspecified),
                            MeetingPlace = "Ambasada lokalne demokaratije",
                            MeetingTheme = "Odnos volontera i djece"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Roncadelle",
                            City = "Zavidovici",
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2809),
                            EventId = 3,
                            MeetingDate = new DateTime(2022, 9, 17, 4, 27, 0, 0, DateTimeKind.Unspecified),
                            MeetingPlace = "Ambasada lokalne demokaratije",
                            MeetingTheme = "Organizacija radionice u sali Prve osnovne skole"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Roncadelle",
                            City = "Zavidovici",
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2811),
                            EventId = 4,
                            MeetingDate = new DateTime(2022, 9, 5, 23, 33, 0, 0, DateTimeKind.Unspecified),
                            MeetingPlace = "Ambasada lokalne demokaratije",
                            MeetingTheme = "Odnos volontera i djece"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Roncadelle",
                            City = "Zavidovici",
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2813),
                            EventId = 4,
                            MeetingDate = new DateTime(2022, 5, 22, 2, 10, 0, 0, DateTimeKind.Unspecified),
                            MeetingPlace = "Ambasada lokalne demokaratije",
                            MeetingTheme = "Organizacija radionice u sali Prve osnovne skole"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Roncadelle",
                            City = "Zavidovici",
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2814),
                            EventId = 1,
                            MeetingDate = new DateTime(2022, 2, 27, 8, 16, 0, 0, DateTimeKind.Unspecified),
                            MeetingPlace = "Ambasada lokalne demokaratije",
                            MeetingTheme = "Odnos volontera i djece"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Roncadelle",
                            City = "Zavidovici",
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2817),
                            EventId = 6,
                            MeetingDate = new DateTime(2022, 3, 12, 21, 29, 0, 0, DateTimeKind.Unspecified),
                            MeetingPlace = "ALD",
                            MeetingTheme = "dnos volontera i djece"
                        });
                });

            modelBuilder.Entity("StraniVari.Core.Entities.PlanAndProgramme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("PlanAndProgramme");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activity = "Radionice",
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2840),
                            EndDate = new DateTime(2021, 9, 25, 19, 1, 0, 0, DateTimeKind.Unspecified),
                            EventId = 2,
                            StartDate = new DateTime(2021, 2, 2, 21, 44, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Activity = "Pauza",
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2844),
                            EndDate = new DateTime(2021, 11, 9, 22, 36, 0, 0, DateTimeKind.Unspecified),
                            EventId = 2,
                            StartDate = new DateTime(2021, 3, 30, 15, 43, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Activity = "Sekcije",
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2846),
                            EndDate = new DateTime(2021, 6, 14, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            StartDate = new DateTime(2021, 3, 14, 16, 38, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Activity = "Bans",
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2848),
                            EndDate = new DateTime(2021, 10, 1, 19, 2, 0, 0, DateTimeKind.Unspecified),
                            EventId = 3,
                            StartDate = new DateTime(2021, 7, 1, 23, 59, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Activity = "Radionice",
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2849),
                            EndDate = new DateTime(2021, 6, 6, 11, 14, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            StartDate = new DateTime(2021, 11, 8, 22, 2, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Activity = "Bans",
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2852),
                            EndDate = new DateTime(2021, 4, 17, 23, 13, 0, 0, DateTimeKind.Unspecified),
                            EventId = 6,
                            StartDate = new DateTime(2021, 1, 21, 2, 1, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("StraniVari.Core.Entities.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Sutjeska",
                            City = "Zavidovici",
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2951),
                            Name = "Druga osnovna skola"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Gostovic",
                            City = "Zavidovici",
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2956),
                            Name = "Osnovna skola Gostovic"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Poljice",
                            City = "Zavidovici",
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2957),
                            Name = "Osnovna skola Poljice"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Safvet-bega Bašagića bb",
                            City = "Zavidovici",
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2959),
                            Name = "Prva osnovna skola"
                        });
                });

            modelBuilder.Entity("StraniVari.Core.Entities.SchoolMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventSchoolId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventSchoolId");

                    b.HasIndex("MaterialId");

                    b.ToTable("SchoolMaterials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2908),
                            EventSchoolId = 4,
                            MaterialId = 2,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2916),
                            EventSchoolId = 4,
                            MaterialId = 8,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2917),
                            EventSchoolId = 4,
                            MaterialId = 9,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2919),
                            EventSchoolId = 5,
                            MaterialId = 11,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2920),
                            EventSchoolId = 4,
                            MaterialId = 18,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2929),
                            EventSchoolId = 4,
                            MaterialId = 20,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2931),
                            EventSchoolId = 11,
                            MaterialId = 20,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("StraniVari.Core.Entities.SchoolVolunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventSchoolId")
                        .HasColumnType("int");

                    b.Property<bool>("TransportNeeded")
                        .HasColumnType("bit");

                    b.Property<int>("VolunteerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventSchoolId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("SchoolVolunteers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2983),
                            EventSchoolId = 3,
                            TransportNeeded = false,
                            VolunteerId = 5
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2986),
                            EventSchoolId = 2,
                            TransportNeeded = true,
                            VolunteerId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2987),
                            EventSchoolId = 5,
                            TransportNeeded = false,
                            VolunteerId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2989),
                            EventSchoolId = 2,
                            TransportNeeded = true,
                            VolunteerId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2990),
                            EventSchoolId = 5,
                            TransportNeeded = false,
                            VolunteerId = 4
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(2993),
                            EventSchoolId = 11,
                            TransportNeeded = false,
                            VolunteerId = 2
                        });
                });

            modelBuilder.Entity("StraniVari.Core.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TripDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(3208),
                            EventId = 6,
                            Place = "Sarajevo",
                            TripDateTime = new DateTime(2021, 3, 3, 1, 19, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("StraniVari.Core.Entities.TripStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TripStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(3233),
                            Status = "Accepted"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(3237),
                            Status = "Declined"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(3238),
                            Status = "InProgress"
                        });
                });

            modelBuilder.Entity("StraniVari.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "16dbd390-db41-47de-b726-f5f9d90bbcd9",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "admin",
                            LastName = "admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "admin@gmail.com",
                            NormalizedUserName = "admin",
                            PasswordHash = "AQAAAAEAACcQAAAAEDHUghaTzFVEj+Lu6qgarzl+SR70Q5y3thhQZbT08mdOdsmbYFe2uR+TQBzxk8JZhA==",
                            PhoneNumber = "111",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = true,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "935e9433-329a-440e-adb8-25be834c0d81",
                            Email = "una2@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "una",
                            LastName = "una",
                            LockoutEnabled = false,
                            NormalizedEmail = "user2@gmail.com",
                            NormalizedUserName = "una2",
                            PasswordHash = "AQAAAAEAACcQAAAAEPh7RPrnb7PqRRIsSyKFo7CJ8nLNnoWeyt8KJGV7EuGIEX0hIXs70+Zuv/hhDwKzVQ==",
                            PhoneNumber = "111",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = true,
                            UserName = "una2"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0268e47e-9988-470a-905e-a2117e60e34c",
                            Email = "una3@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "una",
                            LastName = "una",
                            LockoutEnabled = false,
                            NormalizedEmail = "user3@gmail.com",
                            NormalizedUserName = "una3",
                            PasswordHash = "AQAAAAEAACcQAAAAEPh7RPrnb7PqRRIsSyKFo7CJ8nLNnoWeyt8KJGV7EuGIEX0hIXs70+Zuv/hhDwKzVQ==",
                            PhoneNumber = "111",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = true,
                            UserName = "una3"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "44b3e484-71c1-4a1c-a1c2-f8c5b0867a7c",
                            Email = "una4@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "una",
                            LastName = "una",
                            LockoutEnabled = false,
                            NormalizedEmail = "user4@gmail.com",
                            NormalizedUserName = "una4",
                            PasswordHash = "AQAAAAEAACcQAAAAEPh7RPrnb7PqRRIsSyKFo7CJ8nLNnoWeyt8KJGV7EuGIEX0hIXs70+Zuv/hhDwKzVQ==",
                            PhoneNumber = "111",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = true,
                            UserName = "una4"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d6d4d636-cfb3-4f5b-92e0-4da1c4f56860",
                            Email = "una5@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "una",
                            LastName = "una",
                            LockoutEnabled = false,
                            NormalizedEmail = "user5@gmail.com",
                            NormalizedUserName = "una5",
                            PasswordHash = "AQAAAAEAACcQAAAAEPh7RPrnb7PqRRIsSyKFo7CJ8nLNnoWeyt8KJGV7EuGIEX0hIXs70+Zuv/hhDwKzVQ==",
                            PhoneNumber = "111",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = true,
                            UserName = "una5"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "39b020d2-9a83-4d20-a12b-b74fcdad6ac4",
                            Email = "una6@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "una",
                            LastName = "una",
                            LockoutEnabled = false,
                            NormalizedEmail = "user6@gmail.com",
                            NormalizedUserName = "una6",
                            PasswordHash = "AQAAAAEAACcQAAAAEPh7RPrnb7PqRRIsSyKFo7CJ8nLNnoWeyt8KJGV7EuGIEX0hIXs70+Zuv/hhDwKzVQ==",
                            PhoneNumber = "111",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = true,
                            UserName = "una6"
                        });
                });

            modelBuilder.Entity("StraniVari.Core.Entities.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDateOfVolunteering")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Volunteers");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Address = "Ulica zlatnih ljiljana",
                            City = "Zavidovici",
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(3088),
                            DateOfBirth = new DateTime(2022, 4, 20, 14, 20, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Semina",
                            LastName = "Sinanovic",
                            StartDateOfVolunteering = new DateTime(2022, 2, 8, 16, 28, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Ulica 4.manevarskog bataljona",
                            City = "Zavidovici",
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(3093),
                            DateOfBirth = new DateTime(2022, 2, 26, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ajna",
                            LastName = "Tanovic",
                            StartDateOfVolunteering = new DateTime(2022, 4, 4, 11, 27, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Ulica zlatnih ljiljana",
                            City = "Zavidovici",
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(3095),
                            DateOfBirth = new DateTime(2022, 2, 13, 5, 29, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Elda",
                            LastName = "Bratanovic",
                            StartDateOfVolunteering = new DateTime(2022, 10, 19, 10, 56, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Ulica 4.manevarskog bataljona",
                            City = "Zavidovici",
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(3097),
                            DateOfBirth = new DateTime(2022, 9, 11, 23, 6, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Una",
                            LastName = "Milicevic",
                            StartDateOfVolunteering = new DateTime(2022, 9, 6, 7, 47, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Address = "Ulica zlatnih ljiljana",
                            City = "Zavidovici",
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(3098),
                            DateOfBirth = new DateTime(2022, 9, 3, 1, 1, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Edvin",
                            LastName = "Joldic",
                            StartDateOfVolunteering = new DateTime(2022, 2, 6, 17, 13, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("StraniVari.Core.Entities.VolunteerTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<int>("VolunteerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("TripId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("VolunteerTrip");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(3253),
                            StatusId = 3,
                            TripId = 1,
                            VolunteerId = 5
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 6, 22, 15, 40, 7, 679, DateTimeKind.Local).AddTicks(3257),
                            StatusId = 3,
                            TripId = 1,
                            VolunteerId = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("StraniVari.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("StraniVari.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StraniVari.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("StraniVari.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StraniVari.Core.Entities.Administrator", b =>
                {
                    b.HasOne("StraniVari.Core.Entities.User", "User")
                        .WithOne("Administrator")
                        .HasForeignKey("StraniVari.Core.Entities.Administrator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StraniVari.Core.Entities.EventSchool", b =>
                {
                    b.HasOne("StraniVari.Core.Entities.Event", "Event")
                        .WithMany("EventSchools")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StraniVari.Core.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("School");
                });

            modelBuilder.Entity("StraniVari.Core.Entities.Notification", b =>
                {
                    b.HasOne("StraniVari.Core.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("StraniVari.Core.Entities.PlanAndProgramme", b =>
                {
                    b.HasOne("StraniVari.Core.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("StraniVari.Core.Entities.SchoolMaterial", b =>
                {
                    b.HasOne("StraniVari.Core.Entities.EventSchool", "EventSchool")
                        .WithMany()
                        .HasForeignKey("EventSchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StraniVari.Core.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventSchool");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("StraniVari.Core.Entities.SchoolVolunteer", b =>
                {
                    b.HasOne("StraniVari.Core.Entities.EventSchool", "EventSchool")
                        .WithMany("SchoolVolunteers")
                        .HasForeignKey("EventSchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StraniVari.Core.Entities.Volunteer", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventSchool");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("StraniVari.Core.Entities.Trip", b =>
                {
                    b.HasOne("StraniVari.Core.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("StraniVari.Core.Entities.Volunteer", b =>
                {
                    b.HasOne("StraniVari.Core.Entities.User", "User")
                        .WithOne("Volunteer")
                        .HasForeignKey("StraniVari.Core.Entities.Volunteer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StraniVari.Core.Entities.VolunteerTrip", b =>
                {
                    b.HasOne("StraniVari.Core.Entities.TripStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StraniVari.Core.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StraniVari.Core.Entities.Volunteer", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("Trip");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("StraniVari.Core.Entities.Event", b =>
                {
                    b.Navigation("EventSchools");
                });

            modelBuilder.Entity("StraniVari.Core.Entities.EventSchool", b =>
                {
                    b.Navigation("SchoolVolunteers");
                });

            modelBuilder.Entity("StraniVari.Core.Entities.User", b =>
                {
                    b.Navigation("Administrator")
                        .IsRequired();

                    b.Navigation("Volunteer")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
