version: '3'
services:
#mssql docker
  stranivari-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - stranivarinet

  stranivari-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=stranivari-sql,1433;Database=StraniVari;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 5000:80
    networks:
      - stranivarinet      
    links:
      - stranivari-sql
    depends_on:
      - stranivari-sql
      
networks:
  stranivarinet:
    driver: bridge      